---

#almalinux8 - almalinux9
#java-17-openjdk

#centos7
#java-latest-openjdk

- name: Install openjdk18 on Centos7
  package:
    name: java-latest-openjdk
    state: present
  when: ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] == "7"
  tags: tomcat

- name: Install openjdk17 
  package:
    name: java-17-openjdk
    state: present
  when: (ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] == "8") or (ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] == "9")
  tags: tomcat

- name: add group "tomcat"
  group: name=tomcat
  tags: tomcat

- name: add user "tomcat"
  user: name=tomcat group=tomcat home={{ tomcat_dir }} createhome=no
  tags: tomcat

- name: Download Tomcat version
  get_url: url=https://dlcdn.apache.org/tomcat/{{ tomcat_branch }}/v{{ tomcat_version }}/bin/{{ tomcat_package }} dest={{ tomcat_install_path }}/{{ tomcat_package }}
  tags: tomcat

- name: Extract archive
  command: chdir=/usr/share /bin/tar xvf {{ tomcat_install_path }}/{{ tomcat_package }} -C /opt/ creates={{ tomcat_install_path }}/{{tomcat_final}}
  tags: tomcat

- name: Symlink install directory
  file: src={{ tomcat_install_path }}/{{ tomcat_final }} path={{ tomcat_dir }} state=link
  tags: tomcat

- name: Change Ownership of Tomcat installation
  file: path={{ tomcat_dir }} owner={{ tomcat_user }} group={{ tomcat_group }} state=directory recurse=yes
  tags: tomcat

- name: Configure Tomcat server
  template: src=server.xml dest={{ tomcat_dir }}/conf
  notify: restart tomcat
  tags: tomcat

- name: Configure Tomcat user
  template: src=tomcat-users.xml dest={{ tomcat_dir }}/conf
  notify: restart tomcat
  tags: tomcat

- name: Configure Tomcat manager console
  template: src=context.xml dest={{ tomcat_dir }}/webapps/manager/META-INF
  notify: restart tomcat
  tags: tomcat


- name: Adding port 8080/tcp for tomcat
  firewalld:
    port: 8080/tcp
    permanent: true
    immediate: true
    state: enabled 
  notify: Reloading firewalld rules
  tags: tomcat

- name: Copy tomcat service into systemd
  template:
    src: tomcat.service.j2
    dest: /usr/lib/systemd/system/tomcat.service
  tags: tomcat

- name: systemd daemon reload
  systemd: daemon_reload=yes
  tags: tomcat

- name: Enable tomcat at boot and start
  systemd:
    name: tomcat.service
    state: started
    enabled: True
  tags: tomcat





