---

- name: upgrade all packages 
  yum:
    name: "*"
    state: latest

- name: Install htop
  package: 
    name: htop
    state: present

- name: adding firewall rules for ntp service
  command: firewall-cmd --add-service=ntp --permanent 

- name: adding firewall rules for http service
  command: firewall-cmd --add-service=http --permanent 

- name: adding firewall rules for https service
  command: firewall-cmd --add-service=https --permanent 

- name: adding firewall rules for 8080/tcp 
  command: firewall-cmd --add-port=8080/tcp --permanent 
  notify: Reloading firewalld rules

- name: Ensure NTP-related packages is installed
  package: 
    name: ntp
    state: present

- name: Ensure tzdata package is installed (Linux).
  package:
    name: tzdata
    state: present

- name: Ensure ntp is running and enabled as configured
  service:
    name: ntpd
    state: started
    enabled: yes
  when: ntp_enabled  


- name: Ensure ntp is stopped and disabled as configured
  service:
    name: ntpd
    state: stopped
    enabled: no
  when: not ntp_enabled 

- name: Generate ntp.conf file
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
  when: ntp_manage_config 

- name: Reload ntp daemon
  systemd:
    name: ntpd
    state: restarted
